import { currentLocale, type LocaleCode } from './index'

const KO = {
  forecastProgress: '선택 {current}/{total}',
  turnsLater: '{count}턴 뒤', first: '선공', second: '후공', expectedDamage: '예상 피해 {value}', expectedDamageRange: '예상 피해 {min}~{max}',
  forecastMySentence: '내 문장', forecastLastSentence: '직전 문장', forecastWaiting: '단어를 고르는 중', forecastAttack: '공격', forecastGuard: '방어', forecastHeal: '회복', forecastDebuff: '약화', forecastTargets: '대상 {count}', forecastSelf: '자신', forecastContextValue: '문맥 예상 {value}', forecastExact: '깡 {base} × 배율 {mult} = {total}', forecastEnemy: '다음 적 행동', forecastEnemyAction: '{name} · {timing}', forecastTargetPlayer: '나 1명', forecastRawDamage: '피해 {min}~{max}', forecastHpAfter: '방어 후 체력 {min}~{max}', forecastPierce: '방어 관통', forecastMagicBlock: '매직실드로 차단', forecastGuardBlock: '방어로 차단', forecastGuardShatter: '방어 성공 · 그로기',
  correctedEnding: '고쳐 쓴 결말', preparesSentence: '문장을 준비한다', nextBossSentence: '다음 보스 문장', continuedSentence: '이어지는 문장',
  mantisSubject: '사마귀가', mantisStaggerModifier: '충격을 견디지 못하고', mantisStaggerVerb: '휘청거린다', damageTakenMult: '받는 피해 ×{value}', scheduledAttackSkip: '예정 공격 1회 스킵',
  mantisGather: '온 힘을 모아', mantisRaise: '큰낫을 치켜든다', noDamageThisAction: '이번 행동 피해 없음', nextScythe: '다음 문장: 큰낫 내려베기',
  mantisBreakGuard: '방어를 부수며', mantisSlam: '큰낫을 내려벤다', requiredGuard: '필요 방어 {value}', successGroggy: '성공: 피해 0 · 그로기', failLifesteal: '실패: 체력 피해의 절반 흡혈',
  mantisSharp: '날카롭게', mantisSwing: '낫을 휘두른다', sorrowDamage: '슬픔 피해 ×1.25',
  queenSubject: '여왕벌이', queenWithWorkers: '여왕벌과 {workers}이', queenStagger: '홀로 비틀거리며', queenRest: '숨을 고른다', nextActionSkip: '다음 행동 스킵', respawnWorkers: '이후 일벌 넷 재소환',
  workerZero: '일벌 영', workerOne: '일벌 하나', workerTwo: '일벌 둘', workerThree: '일벌 셋', workerFour: '일벌 넷', workerCount: '일벌 {count}',
  throughShield: '방패의 틈으로', fromFront: '정면에서', queenSting: '독침을 찌른다', surroundedByWorkers: '{workers}에게 둘러싸여', queenHide: '모습을 감춘다',
  bodyInvulnerable: '본체 무적', areaPierce: '범위·관통: 빠른 전멸', angerSingle: '분노 단일: 퇴치 반동 ×2', guardPierce: '방어 관통',
  spiderSubject: '장로거미가', beyondGuard: '방패 너머까지', tightenWeb: '거미줄을 조인다', sealCount: '봉인 {current}/{max}', currentWeakness: '현재 약점 {weakness}', weaknessAction: '약점 행동: 봉인 -1', weaknessComboPierce: '약점+관용구 공격: 다음 부위 관통', bodyNoWeakness: '본체에는 약점 없음',
  spiderEnding: '결말을 고쳐 쓴다', spiderErase: '{weakness}을 지우고', spiderSwallow: '{weakness}을 삼키고', spiderEntangle: '{weakness}을 얽고', spiderBind: '{weakness}을 묶고',
  manuscriptAria: '장로거미가 훼손 중인 문장', damagedLongSentence: '훼손 중인 긴 문장', executeSoon: '곧 실행', endingRevision: '결말 수정', enemyIntent: '적의 의도', roleSubject: '주어', roleModifier: '수식', roleObject: '목적', roleAction: '행동', bossBattleInfo: '{boss} 전투 정보',
  sealCard: '장로거미가 네 문장에서 「{word}」 카드를 실로 묶었다.', sealSlot: '장로거미가 다음 {slot} 카드를 묶으려 한다.', webMiss: '선택 가능한 단어를 남기기 위해 거미줄이 빗나갔다.', releaseSeals: '현재 다리의 약점을 문장에 담아 카드 봉인 {count}개를 풀었다.', weakenWeb: '약점에 맞는 문장이 거미줄 한 겹을 고쳐 썼다.', shakeClause: '약점에 맞는 문장이 장로거미의 구절을 흔들었다.',
  weaknessShift: '다음 다리의 약점이 「{weakness}」으로 바뀌었다.', nextLegRecover: '한 구절을 지웠다. 다음에는 {weakness} 되찾아야 한다.', allClausesErased: '네 감정을 묶던 네 구절을 모두 지웠다.', workersGone: '일벌이 모두 흩어져 공격 문장이 지워졌다.', workersErased: '일벌 {count}마리가 문장에서 지워졌다.', mantisFailed: '「내려벤다」를 막지 못해 사마귀가 상처의 먹물을 빨아들였다.', mantisCorrected: '「큰낫을 내려벤다」를 지우고 「휘청거린다」로 고쳐 썼다.',
} as const

export type EnemySentenceTextKey = keyof typeof KO
type ForeignLocale = Exclude<LocaleCode, 'ko'>

const FOREIGN: Record<ForeignLocale, Record<EnemySentenceTextKey, string>> = {
  en: {
    forecastProgress:'Selected {current}/{total}',
    turnsLater:'in {count} turns', first:'First strike', second:'Second strike', expectedDamage:'Expected damage {value}', expectedDamageRange:'Expected damage {min}–{max}', correctedEnding:'Rewritten ending', preparesSentence:'Preparing a sentence', nextBossSentence:'Next boss sentence', continuedSentence:'Continuing sentence',
    forecastMySentence:'My sentence', forecastLastSentence:'Last sentence', forecastWaiting:'Choosing words', forecastAttack:'Attack', forecastGuard:'Guard', forecastHeal:'Heal', forecastDebuff:'Weaken', forecastTargets:'Targets {count}', forecastSelf:'Self', forecastContextValue:'Context estimate {value}', forecastExact:'Base {base} × Mult {mult} = {total}', forecastEnemy:'Next enemy action', forecastEnemyAction:'{name} · {timing}', forecastTargetPlayer:'Me ×1', forecastRawDamage:'Damage {min}–{max}', forecastHpAfter:'HP after Guard {min}–{max}', forecastPierce:'Pierces Guard', forecastMagicBlock:'Blocked by Magic Shield', forecastGuardBlock:'Blocked by Guard', forecastGuardShatter:'Guard success · Exposed',
    mantisSubject:'The Mantis', mantisStaggerModifier:'reels from the impact and', mantisStaggerVerb:'staggers', damageTakenMult:'Damage taken ×{value}', scheduledAttackSkip:'Skips 1 scheduled attack', mantisGather:'gathers all its strength and', mantisRaise:'raises the great scythe', noDamageThisAction:'No damage this action', nextScythe:'Next sentence: Great Scythe Slam', mantisBreakGuard:'shatters Guard and', mantisSlam:'slams down the great scythe', requiredGuard:'Required Guard {value}', successGroggy:'Success: 0 damage · Exposed', failLifesteal:'Failure: drains half the HP damage', mantisSharp:'sharply', mantisSwing:'swings its scythe', sorrowDamage:'Sorrow damage ×1.25',
    queenSubject:'The Queen Bee', queenWithWorkers:'The Queen Bee and {workers}', queenStagger:'reels alone and', queenRest:'catches her breath', nextActionSkip:'Skips next action', respawnWorkers:'Then resummons four workers', workerZero:'no workers', workerOne:'one worker', workerTwo:'two workers', workerThree:'three workers', workerFour:'four workers', workerCount:'{count} workers', throughShield:'through a gap in the shield', fromFront:'from the front', queenSting:'thrust their stingers', surroundedByWorkers:'surrounded by {workers}', queenHide:'hides from sight', bodyInvulnerable:'Main body invulnerable', areaPierce:'Area · Pierce: faster wipe', angerSingle:'Single Anger: backlash ×2', guardPierce:'Pierces Guard',
    spiderSubject:'The Elder Spider', beyondGuard:'past your Guard', tightenWeb:'tightens the web', sealCount:'Seals {current}/{max}', currentWeakness:'Current weakness: {weakness}', weaknessAction:'Weakness action: Seal −1', weaknessComboPierce:'Weakness + combo attack: pierce next part', bodyNoWeakness:'The body has no weakness', spiderEnding:'rewrites the ending', spiderErase:'erases {weakness}', spiderSwallow:'swallows {weakness}', spiderEntangle:'entangles {weakness}', spiderBind:'binds {weakness}', manuscriptAria:'Sentence being corrupted by the Elder Spider', damagedLongSentence:'Long sentence being corrupted', executeSoon:'Executes soon', endingRevision:'Ending revised', enemyIntent:'Enemy intent', roleSubject:'Subject', roleModifier:'Modifier', roleObject:'Object', roleAction:'Action', bossBattleInfo:'{boss} battle information',
    sealCard:'The Elder Spider bound “{word}” in your sentence with thread.', sealSlot:'The Elder Spider is about to bind the next {slot} card.', webMiss:'The web missed so at least one word would remain selectable.', releaseSeals:'A sentence matching the current leg weakness released {count} card seals.', weakenWeb:'A sentence matching the weakness rewrote one layer of web.', shakeClause:'A sentence matching the weakness shook the Elder Spider’s clause.', weaknessShift:'The next leg’s weakness changed to “{weakness}”.', nextLegRecover:'One clause was erased. Recover {weakness} next.', allClausesErased:'All four clauses that bound your emotions were erased.', workersGone:'All workers scattered, erasing the attack sentence.', workersErased:'{count} workers were erased from the sentence.', mantisFailed:'The Mantis drank the ink of the wound after “slams down” was not blocked.', mantisCorrected:'Erased “slams down the great scythe” and rewrote it as “staggers”.',
  },
  ja: {
    forecastProgress:'選択 {current}/{total}',
    turnsLater:'{count}ターン後', first:'先攻', second:'後攻', expectedDamage:'予想ダメージ {value}', expectedDamageRange:'予想ダメージ {min}～{max}', correctedEnding:'書き直した結末', preparesSentence:'文を準備している', nextBossSentence:'次のボス文', continuedSentence:'続く文',
    forecastMySentence:'自分の文', forecastLastSentence:'直前の文', forecastWaiting:'単語を選択中', forecastAttack:'攻撃', forecastGuard:'防御', forecastHeal:'回復', forecastDebuff:'弱体化', forecastTargets:'対象 {count}', forecastSelf:'自分', forecastContextValue:'文脈予想 {value}', forecastExact:'基礎 {base} × 倍率 {mult} = {total}', forecastEnemy:'次の敵行動', forecastEnemyAction:'{name} · {timing}', forecastTargetPlayer:'自分1人', forecastRawDamage:'ダメージ {min}～{max}', forecastHpAfter:'防御後HP {min}～{max}', forecastPierce:'防御貫通', forecastMagicBlock:'マジックシールドで防御', forecastGuardBlock:'防御で無効', forecastGuardShatter:'防御成功 · グロッキー',
    mantisSubject:'カマキリが', mantisStaggerModifier:'衝撃に耐えきれず', mantisStaggerVerb:'よろめく', damageTakenMult:'受けるダメージ ×{value}', scheduledAttackSkip:'予定攻撃を1回スキップ', mantisGather:'全力を集めて', mantisRaise:'大鎌を振り上げる', noDamageThisAction:'この行動のダメージなし', nextScythe:'次の文：大鎌の振り下ろし', mantisBreakGuard:'防御を砕きながら', mantisSlam:'大鎌を振り下ろす', requiredGuard:'必要防御 {value}', successGroggy:'成功：ダメージ0・グロッキー', failLifesteal:'失敗：HPダメージの半分を吸収', mantisSharp:'鋭く', mantisSwing:'鎌を振るう', sorrowDamage:'悲しみダメージ ×1.25',
    queenSubject:'女王蜂が', queenWithWorkers:'女王蜂と{workers}が', queenStagger:'ひとりでよろめきながら', queenRest:'息を整える', nextActionSkip:'次の行動をスキップ', respawnWorkers:'その後、働き蜂4匹を再召喚', workerZero:'働き蜂0匹', workerOne:'働き蜂1匹', workerTwo:'働き蜂2匹', workerThree:'働き蜂3匹', workerFour:'働き蜂4匹', workerCount:'働き蜂{count}匹', throughShield:'盾の隙間から', fromFront:'正面から', queenSting:'毒針を突き刺す', surroundedByWorkers:'{workers}に囲まれて', queenHide:'姿を隠す', bodyInvulnerable:'本体無敵', areaPierce:'範囲・貫通：素早く全滅', angerSingle:'怒り単体：反動 ×2', guardPierce:'防御貫通',
    spiderSubject:'長老グモが', beyondGuard:'盾の向こうまで', tightenWeb:'蜘蛛の糸を締める', sealCount:'封印 {current}/{max}', currentWeakness:'現在の弱点 {weakness}', weaknessAction:'弱点行動：封印 −1', weaknessComboPierce:'弱点＋慣用句攻撃：次の部位を貫通', bodyNoWeakness:'本体に弱点なし', spiderEnding:'結末を書き直す', spiderErase:'{weakness}を消して', spiderSwallow:'{weakness}を飲み込み', spiderEntangle:'{weakness}を絡めて', spiderBind:'{weakness}を縛って', manuscriptAria:'長老グモが傷つけている文', damagedLongSentence:'傷つけられている長い文', executeSoon:'まもなく実行', endingRevision:'結末を修正', enemyIntent:'敵の意図', roleSubject:'主語', roleModifier:'修飾', roleObject:'目的語', roleAction:'行動', bossBattleInfo:'{boss}の戦闘情報',
    sealCard:'長老グモが君の文の「{word}」カードを糸で縛った。', sealSlot:'長老グモが次の{slot}カードを縛ろうとしている。', webMiss:'選べる言葉を残すため、蜘蛛の糸は外れた。', releaseSeals:'現在の脚の弱点を文に込め、カードの封印を{count}個解いた。', weakenWeb:'弱点に合う文が蜘蛛の糸を一層書き直した。', shakeClause:'弱点に合う文が長老グモの節を揺さぶった。', weaknessShift:'次の脚の弱点が「{weakness}」に変わった。', nextLegRecover:'一つの節を消した。次は{weakness}を取り戻そう。', allClausesErased:'感情を縛っていた四つの節をすべて消した。', workersGone:'働き蜂がすべて散り、攻撃文が消えた。', workersErased:'働き蜂{count}匹が文から消えた。', mantisFailed:'「振り下ろす」を防げず、カマキリが傷のインクを吸い取った。', mantisCorrected:'「大鎌を振り下ろす」を消し、「よろめく」に書き直した。',
  },
  ru: {
    forecastProgress:'Выбрано {current}/{total}',
    turnsLater:'через {count} ход.', first:'Первый ход', second:'Второй ход', expectedDamage:'Ожидаемый урон: {value}', expectedDamageRange:'Ожидаемый урон: {min}–{max}', correctedEnding:'Переписанный финал', preparesSentence:'Готовит фразу', nextBossSentence:'Следующая фраза босса', continuedSentence:'Продолжение фразы',
    forecastMySentence:'Моя фраза', forecastLastSentence:'Прошлая фраза', forecastWaiting:'Выбор слов', forecastAttack:'Атака', forecastGuard:'Защита', forecastHeal:'Лечение', forecastDebuff:'Ослабление', forecastTargets:'Целей: {count}', forecastSelf:'На себя', forecastContextValue:'Оценка контекста: {value}', forecastExact:'Основа {base} × Множ. {mult} = {total}', forecastEnemy:'Следующее действие врага', forecastEnemyAction:'{name} · {timing}', forecastTargetPlayer:'Я · 1 цель', forecastRawDamage:'Урон {min}–{max}', forecastHpAfter:'ОЗ после Защиты {min}–{max}', forecastPierce:'Пробивает Защиту', forecastMagicBlock:'Блок магическим щитом', forecastGuardBlock:'Блок Защитой', forecastGuardShatter:'Защита успешна · Уязвимость',
    mantisSubject:'Богомол', mantisStaggerModifier:'не выдерживает удара и', mantisStaggerVerb:'шатается', damageTakenMult:'Получаемый урон ×{value}', scheduledAttackSkip:'Пропускает 1 запланированную атаку', mantisGather:'собирает все силы и', mantisRaise:'поднимает большую косу', noDamageThisAction:'Это действие не наносит урон', nextScythe:'Следующая фраза: удар большой косой', mantisBreakGuard:'ломает Защиту и', mantisSlam:'обрушивает большую косу', requiredGuard:'Нужно Защиты: {value}', successGroggy:'Успех: 0 урона · Уязвимость', failLifesteal:'Провал: поглощает половину урона по ОЗ', mantisSharp:'резко', mantisSwing:'взмахивает косой', sorrowDamage:'Урон Печали ×1,25',
    queenSubject:'Пчелиная матка', queenWithWorkers:'Пчелиная матка и {workers}', queenStagger:'шатается в одиночестве и', queenRest:'переводит дух', nextActionSkip:'Пропускает следующее действие', respawnWorkers:'Затем вновь призывает четырёх рабочих', workerZero:'нет рабочих', workerOne:'одна рабочая пчела', workerTwo:'две рабочие пчелы', workerThree:'три рабочие пчелы', workerFour:'четыре рабочие пчелы', workerCount:'рабочих пчёл: {count}', throughShield:'через щель в щите', fromFront:'спереди', queenSting:'вонзают жала', surroundedByWorkers:'в окружении: {workers}', queenHide:'скрывается из виду', bodyInvulnerable:'Матка неуязвима', areaPierce:'Область · Пробитие: быстрое уничтожение', angerSingle:'Одиночный Гнев: отдача ×2', guardPierce:'Пробивает Защиту',
    spiderSubject:'Старый паук', beyondGuard:'сквозь Защиту', tightenWeb:'затягивает паутину', sealCount:'Печати: {current}/{max}', currentWeakness:'Текущая слабость: {weakness}', weaknessAction:'Действие по слабости: Печать −1', weaknessComboPierce:'Слабость + комбо: пробитие следующей части', bodyNoWeakness:'У тела нет слабости', spiderEnding:'переписывает финал', spiderErase:'стирает {weakness}', spiderSwallow:'поглощает {weakness}', spiderEntangle:'опутывает {weakness}', spiderBind:'связывает {weakness}', manuscriptAria:'Фраза, которую портит Старый паук', damagedLongSentence:'Искажённая длинная фраза', executeSoon:'Скоро исполнится', endingRevision:'Финал исправлен', enemyIntent:'Намерение врага', roleSubject:'Подлежащее', roleModifier:'Определение', roleObject:'Дополнение', roleAction:'Действие', bossBattleInfo:'Боевые сведения: {boss}',
    sealCard:'Старый паук связал нитью карту «{word}» в вашей фразе.', sealSlot:'Старый паук собирается связать следующую карту «{slot}».', webMiss:'Паутина промахнулась, чтобы осталось хотя бы одно доступное слово.', releaseSeals:'Фраза со слабостью текущей ноги сняла печати с карт: {count}.', weakenWeb:'Фраза по слабости переписала один слой паутины.', shakeClause:'Фраза по слабости поколебала часть фразы Старого паука.', weaknessShift:'Слабость следующей ноги изменилась на «{weakness}».', nextLegRecover:'Одна часть фразы стёрта. Теперь верните «{weakness}».', allClausesErased:'Все четыре части, связывавшие ваши эмоции, стёрты.', workersGone:'Все рабочие разлетелись, и атакующая фраза стёрлась.', workersErased:'Из фразы стёрто рабочих: {count}.', mantisFailed:'Не удалось остановить «обрушивает», и Богомол впитал чернила раны.', mantisCorrected:'«Обрушивает большую косу» стёрто и заменено на «шатается».',
  },
  'zh-Hans': {
    forecastProgress:'已选 {current}/{total}',
    turnsLater:'{count}回合后', first:'先攻', second:'后攻', expectedDamage:'预计伤害 {value}', expectedDamageRange:'预计伤害 {min}～{max}', correctedEnding:'改写后的结局', preparesSentence:'正在准备句子', nextBossSentence:'下一句首领句子', continuedSentence:'后续句子',
    forecastMySentence:'我的句子', forecastLastSentence:'上一句', forecastWaiting:'正在选择单词', forecastAttack:'攻击', forecastGuard:'防御', forecastHeal:'恢复', forecastDebuff:'削弱', forecastTargets:'目标 {count}', forecastSelf:'自己', forecastContextValue:'语境预计 {value}', forecastExact:'基础 {base} × 倍率 {mult} = {total}', forecastEnemy:'敌方下一行动', forecastEnemyAction:'{name} · {timing}', forecastTargetPlayer:'自己1人', forecastRawDamage:'伤害 {min}～{max}', forecastHpAfter:'防御后生命 {min}～{max}', forecastPierce:'贯穿防御', forecastMagicBlock:'由魔法盾抵挡', forecastGuardBlock:'由防御抵挡', forecastGuardShatter:'防御成功 · 破绽',
    mantisSubject:'螳螂', mantisStaggerModifier:'承受不住冲击，', mantisStaggerVerb:'踉跄起来', damageTakenMult:'受到伤害 ×{value}', scheduledAttackSkip:'跳过1次预定攻击', mantisGather:'凝聚全力，', mantisRaise:'举起巨镰', noDamageThisAction:'本次行动无伤害', nextScythe:'下一句：巨镰下劈', mantisBreakGuard:'击碎防御，', mantisSlam:'挥下巨镰', requiredGuard:'所需防御 {value}', successGroggy:'成功：伤害0 · 破绽', failLifesteal:'失败：吸取生命伤害的一半', mantisSharp:'锐利地', mantisSwing:'挥动镰刀', sorrowDamage:'悲伤伤害 ×1.25',
    queenSubject:'蜂后', queenWithWorkers:'蜂后与{workers}', queenStagger:'独自踉跄着，', queenRest:'调整呼吸', nextActionSkip:'跳过下一次行动', respawnWorkers:'之后重新召唤四只工蜂', workerZero:'零只工蜂', workerOne:'一只工蜂', workerTwo:'两只工蜂', workerThree:'三只工蜂', workerFour:'四只工蜂', workerCount:'{count}只工蜂', throughShield:'从盾牌缝隙中', fromFront:'从正面', queenSting:'刺出毒针', surroundedByWorkers:'被{workers}包围', queenHide:'隐藏身影', bodyInvulnerable:'本体无敌', areaPierce:'范围·贯穿：快速全灭', angerSingle:'愤怒单体：反伤 ×2', guardPierce:'贯穿防御',
    spiderSubject:'长老蜘蛛', beyondGuard:'越过盾牌', tightenWeb:'收紧蛛网', sealCount:'封印 {current}/{max}', currentWeakness:'当前弱点 {weakness}', weaknessAction:'弱点行动：封印 −1', weaknessComboPierce:'弱点＋惯用语攻击：贯穿下一部位', bodyNoWeakness:'本体没有弱点', spiderEnding:'改写结局', spiderErase:'抹去{weakness}', spiderSwallow:'吞下{weakness}', spiderEntangle:'缠住{weakness}', spiderBind:'束缚{weakness}', manuscriptAria:'长老蜘蛛正在破坏的句子', damagedLongSentence:'正在被破坏的长句', executeSoon:'即将执行', endingRevision:'修改结局', enemyIntent:'敌方意图', roleSubject:'主语', roleModifier:'修饰', roleObject:'宾语', roleAction:'行动', bossBattleInfo:'{boss}战斗信息',
    sealCard:'长老蜘蛛用蛛丝绑住了你句子中的“{word}”卡。', sealSlot:'长老蜘蛛正要绑住下一张{slot}卡。', webMiss:'为了保留可选单词，蛛网落空了。', releaseSeals:'句子包含当前腿部弱点，解除了{count}个卡牌封印。', weakenWeb:'符合弱点的句子改写了一层蛛网。', shakeClause:'符合弱点的句子动摇了长老蜘蛛的分句。', weaknessShift:'下一条腿的弱点变为“{weakness}”。', nextLegRecover:'已抹去一个分句，接下来要找回“{weakness}”。', allClausesErased:'束缚你情感的四个分句已全部抹去。', workersGone:'工蜂全部散去，攻击句被抹除了。', workersErased:'{count}只工蜂从句子中被抹除。', mantisFailed:'未能挡住“挥下”，螳螂吸收了伤口的墨水。', mantisCorrected:'抹去“挥下巨镰”，改写为“踉跄起来”。',
  },
  'zh-Hant': {
    forecastProgress:'已選 {current}/{total}',
    turnsLater:'{count}回合後', first:'先攻', second:'後攻', expectedDamage:'預計傷害 {value}', expectedDamageRange:'預計傷害 {min}～{max}', correctedEnding:'改寫後的結局', preparesSentence:'正在準備句子', nextBossSentence:'下一句首領句子', continuedSentence:'後續句子',
    forecastMySentence:'我的句子', forecastLastSentence:'上一句', forecastWaiting:'正在選擇單詞', forecastAttack:'攻擊', forecastGuard:'防禦', forecastHeal:'恢復', forecastDebuff:'削弱', forecastTargets:'目標 {count}', forecastSelf:'自己', forecastContextValue:'語境預計 {value}', forecastExact:'基礎 {base} × 倍率 {mult} = {total}', forecastEnemy:'敵方下一行動', forecastEnemyAction:'{name} · {timing}', forecastTargetPlayer:'自己1人', forecastRawDamage:'傷害 {min}～{max}', forecastHpAfter:'防禦後生命 {min}～{max}', forecastPierce:'貫穿防禦', forecastMagicBlock:'由魔法盾抵擋', forecastGuardBlock:'由防禦抵擋', forecastGuardShatter:'防禦成功 · 破綻',
    mantisSubject:'螳螂', mantisStaggerModifier:'承受不住衝擊，', mantisStaggerVerb:'踉蹌起來', damageTakenMult:'受到傷害 ×{value}', scheduledAttackSkip:'跳過1次預定攻擊', mantisGather:'凝聚全力，', mantisRaise:'舉起巨鐮', noDamageThisAction:'本次行動無傷害', nextScythe:'下一句：巨鐮下劈', mantisBreakGuard:'擊碎防禦，', mantisSlam:'揮下巨鐮', requiredGuard:'所需防禦 {value}', successGroggy:'成功：傷害0 · 破綻', failLifesteal:'失敗：吸取生命傷害的一半', mantisSharp:'銳利地', mantisSwing:'揮動鐮刀', sorrowDamage:'悲傷傷害 ×1.25',
    queenSubject:'蜂后', queenWithWorkers:'蜂后與{workers}', queenStagger:'獨自踉蹌著，', queenRest:'調整呼吸', nextActionSkip:'跳過下一次行動', respawnWorkers:'之後重新召喚四隻工蜂', workerZero:'零隻工蜂', workerOne:'一隻工蜂', workerTwo:'兩隻工蜂', workerThree:'三隻工蜂', workerFour:'四隻工蜂', workerCount:'{count}隻工蜂', throughShield:'從盾牌縫隙中', fromFront:'從正面', queenSting:'刺出毒針', surroundedByWorkers:'被{workers}包圍', queenHide:'隱藏身影', bodyInvulnerable:'本體無敵', areaPierce:'範圍·貫穿：快速全滅', angerSingle:'憤怒單體：反傷 ×2', guardPierce:'貫穿防禦',
    spiderSubject:'長老蜘蛛', beyondGuard:'越過盾牌', tightenWeb:'收緊蛛網', sealCount:'封印 {current}/{max}', currentWeakness:'目前弱點 {weakness}', weaknessAction:'弱點行動：封印 −1', weaknessComboPierce:'弱點＋慣用語攻擊：貫穿下一部位', bodyNoWeakness:'本體沒有弱點', spiderEnding:'改寫結局', spiderErase:'抹去{weakness}', spiderSwallow:'吞下{weakness}', spiderEntangle:'纏住{weakness}', spiderBind:'束縛{weakness}', manuscriptAria:'長老蜘蛛正在破壞的句子', damagedLongSentence:'正在被破壞的長句', executeSoon:'即將執行', endingRevision:'修改結局', enemyIntent:'敵方意圖', roleSubject:'主語', roleModifier:'修飾', roleObject:'賓語', roleAction:'行動', bossBattleInfo:'{boss}戰鬥資訊',
    sealCard:'長老蜘蛛用蛛絲綁住了你句子中的「{word}」卡。', sealSlot:'長老蜘蛛正要綁住下一張{slot}卡。', webMiss:'為了保留可選單詞，蛛網落空了。', releaseSeals:'句子包含目前腿部弱點，解除了{count}個卡牌封印。', weakenWeb:'符合弱點的句子改寫了一層蛛網。', shakeClause:'符合弱點的句子動搖了長老蜘蛛的分句。', weaknessShift:'下一條腿的弱點變為「{weakness}」。', nextLegRecover:'已抹去一個分句，接下來要找回「{weakness}」。', allClausesErased:'束縛你情感的四個分句已全部抹去。', workersGone:'工蜂全部散去，攻擊句被抹除了。', workersErased:'{count}隻工蜂從句子中被抹除。', mantisFailed:'未能擋住「揮下」，螳螂吸收了傷口的墨水。', mantisCorrected:'抹去「揮下巨鐮」，改寫為「踉蹌起來」。',
  },
}

export function enemySentenceText(key: EnemySentenceTextKey, variables: Record<string, string | number> = {}, locale: LocaleCode = currentLocale): string {
  let value: string = locale === 'ko' ? KO[key] : FOREIGN[locale][key]
  for (const [name, replacement] of Object.entries(variables)) value = value.split(`{${name}}`).join(String(replacement))
  return value
}

export function enemySentenceLocalizationErrors(): string[] {
  const errors: string[] = []
  const keys = Object.keys(KO) as EnemySentenceTextKey[]
  for (const [locale, rows] of Object.entries(FOREIGN) as [ForeignLocale, Record<EnemySentenceTextKey, string>][]) {
    for (const key of keys) {
      const text = rows[key]
      if (!text?.trim()) errors.push(`${locale}: enemy sentence ${key} missing`)
      if (/[가-힣]/.test(text)) errors.push(`${locale}: Korean remains in enemy sentence ${key}`)
      const variables = KO[key].match(/\{[^}]+\}/g) ?? []
      for (const variable of variables) if (!text.includes(variable)) errors.push(`${locale}: enemy sentence ${key} lost ${variable}`)
    }
  }
  return errors
}
